#!/bin/bash

# function to get the output of command being run into an array (arr) as well as in stdout

get_cmd_output()
{
	echo $* > /tmp/exe
	bash /tmp/exe > /tmp/out
	
	IFS=$(echo -en "\n\b")
	arr=()
	exec 3</tmp/out
	while read -u 3 -r line
	do
		arr+=($line)
		echo $line
	done
	exec 3<&-
}
